### ISSUE TITLE
share wallet card component with web UI

### ISSUE THREAD

**Issue by olaven** [aridder/pengekrukka#56]
## TODO 
- [x] Accepts color 
- [x] Accepts VC object 
- [x] Accepts icons 
- [x] Renders color 
- [x] Renders expiration 
- [x] Renders icons 
- [x] Renders title 
- [x] Proportions like a credit card
- [ ] matching design in figma 
- [ ] component is used by different pages
